apiVersion: ENC[AES256_GCM,data:m+A=,iv:yjc5u+tUFIDoot/s4jT/j2rqyq1A7EhOjVS5z2yqTLI=,tag:r8GtMPA/SBGVkna6mZpJOQ==,type:str]
kind: ENC[AES256_GCM,data:s5XZMGd4,iv:uX5L9iVzYq5B9i9dw7Ii1ZvWKqPpt93QpqYn4M3dHZ4=,tag:4jNHWwRWfxNsV9+1QS+vVg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BU3QnSLuiXs4MvpdKoVUjkqgkhVCNzs=,iv:kUn7IuY75eUjjjWBwzHUaVj3P2hLWp8XNUgfZJ+sC2o=,tag:STvASM8tKj6AKVJQEcaD1g==,type:str]
    namespace: ENC[AES256_GCM,data:EiNhbOWG1A==,iv:eaUjgBrh7GEMRjkuaX842SIqq9kVL2Y6DS/aBRFd6rw=,tag:wfMRr8imQx4dRDxlXnvoYw==,type:str]
type: ENC[AES256_GCM,data:WWeZ5Tjn,iv:GMq70Lxv5/zH/myMz03ewdvgmV0zJF1DtcyhRCULYt0=,tag:KnoZDuI1Jz2/LsJOv/BzkA==,type:str]
stringData:
    token: ENC[AES256_GCM,data:8+M0dR2fktiuvyaSJOfk9hkSneW8A87xBHoiApFSqEHvfovMqbUMoEttIOhtwtzIgFAKxqKhIFEewSOGKLwbP+GlD2OX2TktDsCu6MmYwpXkrKMe6l2qlVkd7Nl7gzeTGEJZIhuWAEWqYt3jFvY1H5+vprSkhSj0xIU20mzV+P8pOo6yXLasFom22CKNd8wndmX6EoNEuJilxhgoeUglXTfovElfRyWgnCPYdRXjAhIWJPXpmmlNdQ==,iv:PmafPFIGydC7rty8PKoC9u98vUKItsCpx0p1kZr2+j0=,tag:XhuAt+Kf86ZaTg1YGjsGhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1msk44qnlr795tc4m7ddw5z7sue7849nhll4wnx2qt3ruaesgye0q2rmx27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WHhEVVF5NjVndjhxWnRy
            WlEzQUFCSEtRRDR1Z1NrZlhMSEFJYVZxSlVjCnpsTzVIcHhGbTc0RnIrQ0NvMmRo
            aTgwUDloLzVvbTUzQnlsMTQ4RG1WQ1EKLS0tIGlCVVlmeUUzYkF5QldqM1J4RkJF
            Rm1nOVhUa2xqRmtOVTEyeFRrSHdyeWcKXmgeSkpS1jQWP7Q6aph9CyJ595UZniEE
            bTkgGgAnVlCCFLNxueiLc05AtjVX/NNosWJaktnxauqXvGznnzE5zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T02:43:08Z"
    mac: ENC[AES256_GCM,data:KU0PNJyoslUfqhKWUyFqG9bGr/Ef2K7YoV7UwZOtaYTmhAZwJlvCqnuar9nbG5TbXxOvL6Zx7MSwtrRPAdY1xNnYEWJMFJnGVf2rK8NJR9Vq5twGhLgVeBniDMmrQ9Xs9FXLlYlbfgsclQFTIlwKtm3SRzlBC+p6CBxveBJwmrc=,iv:ARqf6JgWgEq+XzXkdthcszOZMwiou37wvNnSzl8eWf8=,tag:oKXzN2P7ugT3RggNvDsmSw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
