apiVersion: ENC[AES256_GCM,data:lOs=,iv:hNCPgC/WEnjjCy+Tc9E0LJYp7hg7RTQGyaRKN9n22M4=,tag:m3D1WXOIWyj+mjQsUnCdPg==,type:str]
kind: ENC[AES256_GCM,data:PlvAtnTe,iv:bfr09fHCeY1EIHBhKkWw5MqwG4AYavk6uwa+3NUSLi4=,tag:u2N8pSNJGZZdoRIQZ39BzA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IsnjEd4utxzRNndOEMWi0+My9KrEA08=,iv:44tCHq1EMYqH2a7xQxPquEy8cScF9Q2s+U8EyIFI4/k=,tag:RbGwAr0w0+By6M61zRTvQg==,type:str]
    namespace: ENC[AES256_GCM,data:HQujNg==,iv:UdyIX71XUvnqJD1Cs7zEENLvfibhEhQAI7nHO07tHDI=,tag:TK1NSHvh5EFcUJtZjRjhaA==,type:str]
type: ENC[AES256_GCM,data:TCTvcfhe,iv:XUAzk6MXqJ5yP2wnyYKXWJj8uZcQ6uek5/qVSMFvKzw=,tag:8M+Bg4akKBYfhR/ShDoJNg==,type:str]
stringData:
    token: ENC[AES256_GCM,data:fLJMC2WQr15UyTTuy0aKkkO7whX5TE4Z0wEi+UzXCbMNCg1StE8zWraUE3Riyhc0e1WUF6OSGXoQg+6nq/pOhF16fqmlf3u0r1o7+cWbMIOA5bUYb4Wuxk9YFAHP8Pnwbo7Z9VoT8i4f5akhhgpMN+lU+W7vFZnuSUJoKzuYh7dXeCMXfg/i7wrbDGij9rRbya2pNZNrGY2vOzcyG0hYrJOLXkE9kJdsc28z2WK2lH3sKodc8WOdWQ==,iv:7G1TsnsLyJT+isQO2WL8GPTbXEQ3gjjfhLT4EDEHXxg=,tag:XsIBBwPNyndsQdYRfxgtJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1msk44qnlr795tc4m7ddw5z7sue7849nhll4wnx2qt3ruaesgye0q2rmx27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZjhORko4bG1xTUtuSzRp
            eDltRmppWFVjVjQxU24zYjB1ZEowUndoQUFrCjZwTGtVUzRwZnJlaEN5SkhFbi9O
            NlNVTjZjc1hkQi8wUUR5NUM0bStqOWMKLS0tIEk2d2ppVHg2V1hHWU4xNEVzRWN1
            cmp0dy9wZytYeFJXMG5va05ZZC9TdDQKoqTm/RQMZjWxuMqcwzBAsEAPNAXbFAuP
            mJVTKOuXNa2EwPNXLmA17xdBCKLcAA6Ijz9gkwKL59ahI9YKAWcZYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T03:34:12Z"
    mac: ENC[AES256_GCM,data:/5kBliA5gDZsd8HOPD+CVRw+n4gy3DK7G8EZLqGnoj//BBOyLYH2Bcp3IqXmB6GEe0gf1u9IGI5SiypETpKSPaRXkdHV90tVSGYozrKPUH+QZbK4c2ZmlL0SIykLjbmWTiBmoa264vjtEeWhIxxEiQCz4wspCTKIy3W/1gdZssM=,iv:DwqtPmvQMFbVRKNWazhz28rTmqDjA8L9ZV36L4s9PCU=,tag:pHT3ltIi15481wSF3yKDGg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
