apiVersion: ENC[AES256_GCM,data:A14=,iv:7+9uhZVAm5lFjP5zrtFT6M8/7KXW/jIAaKkd6DnNZag=,tag:tddFoSAigZTU82HH9s/lsQ==,type:str]
kind: ENC[AES256_GCM,data:4Ro5JP2m,iv:iL3qgsIZVg/Do0m3iV1XcrM59B/1eQFX/k14OX4rFSE=,tag:NRTkcOIBZUYu3Hr8/gnWfQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2FTbvon6NzFpLCxOXijvDKgweeZoFl8=,iv:YC8Kq5LAl5uwjqfw48kvHCh1Hav8niSHGDp1kvhwsh8=,tag:pU48QP0XvncxXh3XS2wL6w==,type:str]
    namespace: ENC[AES256_GCM,data:7D4lCMyd1e8=,iv:d0GRD5Xj/fTk3hlGPQ2cfJ1dWxTrIbgBba5vF+qgDSE=,tag:hAK4wOcO07fxFm42ieKxxw==,type:str]
type: ENC[AES256_GCM,data:+1emLY/C,iv:nIKrEvMYk92zPDVzNmBuStE38hlFW7n32Ic6rsBtA8s=,tag:DwrYfMTHZS3dwO5sgWDA5g==,type:str]
stringData:
    token: ENC[AES256_GCM,data:sG+Bjf1bvP6zHkpoDLaXrLH7vPLflmnponK08q178bm85Pz5ypf36zVb2wS2UG7ps+5ry3c9xisZBHc4VixVXkQPV+3olw5WqTUwBj9C7JuFmogj1dbQYNI13BK6VQ97+YrLWAhoUb2byphuoK/k4BjknH8lGVk8gLQcz/TyK8311NaIwq3EjyJLnk0eJurmnNSFppwc0tIkW0fKAm+X0vpXxsMXd0I5xUTvU/IN056mOjEPDE1iHw==,iv:XGpkBkvWV06kzQ7mrmNZg6DoFn3az8I8i6NhKhFhLCs=,tag:DIUFMTxb630QNWoAdYbIGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1msk44qnlr795tc4m7ddw5z7sue7849nhll4wnx2qt3ruaesgye0q2rmx27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4akdjeGIxVXNRWUd6OWZp
            dkhsVDhxR0E0a3RDb2NKL2ZYUkM3MWt5THg4CmdkakxBUnhKbVplVzhpaDlXNS8w
            YTVzb3ZIREEycUZPZW91VnBZOWhmd28KLS0tIG5sT3lGRVA4OURJQTU4cTdYdUZN
            dzFBNlMra1p1VGp0aHRSY280aDY3TmMKZGv56soEdPXMsAhPm2HSKDaEHiNKsyIG
            /Ox67fGtQ1SOpnHp7QzeEZ1AurbV4yFTug0lBDyDdYpx7eCnhrmB9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T02:53:51Z"
    mac: ENC[AES256_GCM,data:WcBrn4N98Y0L/vSRuUpCR9XmMKMeJK5dJLMZOFDB6HjaAWGay4C0JADBDHRXW2/fqD7/d20DrFfMLxiWpSHFF6Cx7PC6eid3gEI76lK+c9j401wrUTiZOmNA4My+ibF217DIBm0Sq41JtOUnIaGROtyIYoKwgpspi2y4UxKNH24=,iv:yv2HbOirr28QcIeL1cF2Ez9l11oU2vBMQoxrUp+5vZA=,tag:b0o6DLrK5yxHvbW06Fx63A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
