apiVersion: ENC[AES256_GCM,data:aN8=,iv:a+yzwCcZ9mdCq2xNSEHpPVOGfQDaQA/xquIEqI+oZwM=,tag:a2KkLOgfWsSRCVhq7tMHkg==,type:str]
data:
    token: ENC[AES256_GCM,data:ITvFT/X7WHKgdOwzJP6ntAEqqOOAEfI24yoZIeHR8kDbpTC7w2TqpHD4TDXnBewaehv06KM9OMM=,iv:tdomI8hJIWYCEzR4Bek2hp/U8xoORhcCo71HLbeE3cA=,tag:bw3bC4fBITHImrZpzhxAzw==,type:str]
kind: ENC[AES256_GCM,data:seCLfwZd,iv:529sNEWAmhuaO1osHKdnora9ICfpwLznqQ+P7v2RY7Y=,tag:euSD9Km6acPr0X3QiY52tg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MH51m2U1,iv:Ij+CdaVrjfWNr3B4+j4OvDtuvv/smTp+XuKadxwiHdY=,tag:iD67iGaSJcVBt0r0Smmo9w==,type:str]
    namespace: ENC[AES256_GCM,data:tbxUMLw7iQnxoE0=,iv:FI2dcMTHSU3WB1ZO6/BqQbGv/hyNALd2ciZAwK4Xcm4=,tag:x+MGXje8IGTumMtfdcJFDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1msk44qnlr795tc4m7ddw5z7sue7849nhll4wnx2qt3ruaesgye0q2rmx27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxKy9Zc2lWbEdXUXhvb1Bs
            N0ppTVN5cklMRmRqK0x2ZjRPbXhMaDdGS2kwCldsK044V3pRbDB6Wk0xZXRvSU9C
            K1FUVHFnOFVHYlg3ZWMxdkc1bWZpYkEKLS0tIFpwOG9FeUdQUVBCTHBRanFEVExu
            MGtuK3dGZ2w5OVB3NDF1SFJ4MmpuT28K6TqWZB4OxR/Y/1WKCMDrq5hH8mHEw8Xo
            FPwfNgNADaOONXcwO9daSwqchZ8Nba34Mo7wdjwQsNsCASROkc/LhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T21:12:08Z"
    mac: ENC[AES256_GCM,data:mFWpsITTtCYSpk3b5P/VMZOWEtDo3BucRRCd8RIQLULsVxEDfA3wMa9CqYKF+4/hWJVdsbA67SmS1Fr4OB579dvFaGNSF8UZMC4y22+HhelcPggU4lj8cTtrkvj5fYLqurwRIJ90+sTylpM2KB5mg2pba50DhVMXQL9eOydxf9E=,iv:PuMMCiLxQmsh1VcIk18aMNZ7EOMkxW7bxyjfBI5zEx0=,tag:cBl6gHJN4gm8Bk8sJESfgQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
