apiVersion: ENC[AES256_GCM,data:2Jg=,iv:dZcVkMJQh5M4KdSsU2gkRxhgO58x6jOwf8vy7jmjvoQ=,tag:qw3FCRoB49lHt2gbd5GHzg==,type:str]
data:
    token: ENC[AES256_GCM,data:NKV0uWWB2+3hZGhJWh5VnDsGWQjTvFmr+BUBZXgBWTnwGwxTxICWeA0V2WkitbN3t+wzBeGjJvA=,iv:v44DI9Rzb+mHidhRH/QK4PHdJ/4VpMGjB3o5uYDPKzg=,tag:LoRtl8LBwz4CRp6bVI/Ovg==,type:str]
kind: ENC[AES256_GCM,data:xIbgG1uq,iv:nf+JemankqCBcQ3KSQRsC1BiJeog9oanJN74NWc/kNE=,tag:u0S2EKg/BTD5/gOX6qP33A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6m/lfwAz,iv:R+DkDlXTcg1NOPntndiJbQYcuesCSbuXXsrxU/rz45M=,tag:3eygxUrSVmaoKFB2y6OU6g==,type:str]
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1msk44qnlr795tc4m7ddw5z7sue7849nhll4wnx2qt3ruaesgye0q2rmx27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVFl2dVpRWDhpVUtQQW9Z
            N0Y0dkVIUEFqcFNObWVtNlBrZE1KeGRhRDJzCjdnaG82QUlOc0VBRjNVVENyL3hv
            d0hCQWRHaUFSVVBIdFBFV1Z4TlgvVnMKLS0tIHAvbGtQT3pLa1lsMDIrV01Ea0hr
            aFI1bUlTRGd4bzhyTkIyTkJzVkpDc3MKtc7/Jqw+qyAKuNK1m7n2amEXAvpmiA/e
            6RJXDxLCnchBo7k2XD6tHRXTXalP+eWxwwzd21gTvy3gSm3h8nm+tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T20:24:16Z"
    mac: ENC[AES256_GCM,data:mRqScGNOw8D6VwakyL/sKEBygFlGsxP9JPjpkwjFYwGob97uWiiWDTn4lCMFtVIjkAM2zePeXKNDCfJLsy0hCmXLi0b3xAdWpIq0qPNfFzkUz6ORYW30QRREnfPmBedbROpRh+knTLJ0BG9xqzvJFCcQ9Ee2XhC4XYFnVi4z1tA=,iv:YsD8oiaaBN2KQmI804QSTiujsZb8EM9bARzZdcgnu/4=,tag:UBNb/uDuZR6iYasbD32k+A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
