apiVersion: ENC[AES256_GCM,data:ZH0=,iv:pgnC4bKAJLGBaVnxlBmLcei4s8CFUokJopQK+4vRYyA=,tag:jZ8qoRP1ohEYLxfMvB6nPw==,type:str]
data:
    token: ENC[AES256_GCM,data:LEXX0au0nsJbEicVWixx9pdKgDnYvCu1pZRKal+3iszIfoh9d+QrxO5sR6UgsF/SADdTiTWD3Oc=,iv:QZBC4IJLk32fLz1K62odiTenOLRR5d8DyTeeUtNKgGo=,tag:BymmH+kIg44KYfTkM25GUg==,type:str]
kind: ENC[AES256_GCM,data:QqXAX6/9,iv:R1DkY3gmmA3pgvab8MCTF9866jLoQCjuqTW+oKtRpcg=,tag:89XGFdIGCAfl+Xzx6FO0GQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mVviRzwi,iv:DZTF46x7XmYWSi2BSk4F1v4dD78yWThuJ7ispGyC5zs=,tag:AwmIqpF1YRHf/ef38FQYTA==,type:str]
    namespace: ENC[AES256_GCM,data:JstDTKvUM70K5GQ=,iv:bNorULl0lM4jDjkd32aDJauIS5xLPmbCrXiIfkVutzg=,tag:Uduijc9tjxTGTY14hYCrEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1msk44qnlr795tc4m7ddw5z7sue7849nhll4wnx2qt3ruaesgye0q2rmx27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNenNHcEVRL01RTS95cEdm
            cWdIYjRSVkRNeEY3YTQ2clQzVnBLcjFJWVJRCllZVnRjeUwvR241STJteTVpQi82
            L0ZENm9tOVFEK1JZY3k4bXNiaktlQ2MKLS0tIGIya2ovSDJmclBXVzZKMFRrM1U2
            R2k1YXNTNlkxVytUMGlONHhqT1RuSGMK1DxK/NIZXsf8Id3VZfjwxpsBNlBhdiPY
            L7b1Zxj+MddNyMIHRouRdEe4rm9e8AiD75A+AsNjZndI5z1iGqG03Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-27T02:48:44Z"
    mac: ENC[AES256_GCM,data:s6Rx41/nyuHvoImlsVUmUxmGeQ/6kMEhz9BV5KhZVWe5wha6hLWnFkEtKUHiRPOl9AmajIJtqu6W3Zt4PFfeh1D8iXtX0QfJelpM+kpMKIHUiepM2p+sfV+hploHrEU93PUSvgM57Dk3VEmh//OSUhE1cm1TYqt/gP4if9/SuhE=,iv:yY3xj5b59QI19axWUlDgNebBTaKRK5Y81bMVXMieMgI=,tag:VamC1W6ERVNfDamPLISuAA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
