apiVersion: ENC[AES256_GCM,data:DfA=,iv:FzafmoH0DIXNdtUZA4lqdQhEbYFi1IuT6QEAEpWVXJY=,tag:mVI4nYflscMGvkxqy3kxCw==,type:str]
kind: ENC[AES256_GCM,data:pskqM7jF,iv:o/oBMPNJ1pAoI5TbQrpz8DHzzRHlR2ySPTZOsMS3DlM=,tag:NrdX5ZbqAZPeStl9LXFwCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AljUtt9kzC7AunkeMQ==,iv:Pzqst0Uj+kgunF8bySw/sV6Xa2VoaVXv+TVYS25neUM=,tag:7GXkZ4qIaNcI0NTd4+RV9g==,type:str]
    namespace: ENC[AES256_GCM,data:ZZjPIyH+91KoKA==,iv:jcPETNJxlm14IyvSAM3TYZmKw+iYVoC1quk+kizGVhY=,tag:UJR9TnofNqLYg2rdLGSduA==,type:str]
type: ENC[AES256_GCM,data:GPwhOvfi,iv:uJa/Gth9IiMLqTO0Kb6x66e1A3npTEwfhrdvdm/yBAs=,tag:n0BvTTCAWjZulP7fwm5aeQ==,type:str]
data:
    admin-user: ENC[AES256_GCM,data:gGynhmJP4g==,iv:fpPRpwIDeySB+rGB3s+lbhpmuig20N2668Fzdyj0x3c=,tag:YAKA5MkrFPb9Wf3dMBuNCw==,type:str]
    admin-password: ENC[AES256_GCM,data:4kaHGdoXydI3z6RdVlOjVqQvo4CzJ5Wm,iv:hu7+riu7Cscv7SQ5xNOvgjGML4y5F4g2tE3qmgx36OY=,tag:nw4AepONRf01Lsm1zXANQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1msk44qnlr795tc4m7ddw5z7sue7849nhll4wnx2qt3ruaesgye0q2rmx27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaUp5QUE5RHRsSG1sNkt6
            dyswcm9ZakNZSkZtYVlSWjE3cFlFMTlNQUJRCnM2OWlyVzd3YnJ1K1VqblRJaVEr
            Q2NXSUlvcDZFYXMzYWozVlUzK2hzUG8KLS0tIEhEWW5KaEZLTytUdG9mMnEwblRJ
            VEF5UGxsWmdOYmVMVzNGVVRyR0ZsRFUKR9iO6aeSuEOhrGPIJ1/DnbS5Kg8GeRad
            FUK0qN9onffaz1CCtGMBFVikW3rTo4/GMORRterJloWRxAPW0JjSUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T04:23:51Z"
    mac: ENC[AES256_GCM,data:ByjEombjuzjc2nKlNNdv9k5XqwiLLztRNS/zA+WzqzFnBMkt/26szmBCW8pdgVeJBpaLIoib2bIc2j25BhaB/vE0oXMA06WHKvcYx6f7BPtG6oggomG82CtW4GB41OvqYPd5DrSFtqGyobYg422bE6LS/xqlmgYtXJ0YUHv5HOc=,iv:BNCOVtjDyi+CWYQAcAb2J+Ief5MDburWIwmmQdKG4qM=,tag:e7WNvuon/T4uooTprIWWlw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
