apiVersion: ENC[AES256_GCM,data:T/Y=,iv:TFVyvDlUDOLwOIPZBsSw8CzqGfK5CXwpY2I9jJD0kEA=,tag:fqDNoVo9OpoLps8vdcjf3w==,type:str]
kind: ENC[AES256_GCM,data:BIt0SKCE,iv:4v4XlUDdGWI265FJQZZE/gw2lJK0ziMLontgWxM0TGY=,tag:Ab23QseWVMmyqwNo2BbZbA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qLa6s4eQ/n6SlNsruQ==,iv:vbe4Ejjuiv/H1g+7y2LhrJgJmguCZls2t9amwp6b2Dk=,tag:0GPbcTl9RxoPTOJsH0EBhQ==,type:str]
    namespace: ENC[AES256_GCM,data:/4IB3TmRP7QcuQ==,iv:g0LxJJ7NblLGK4jJ4gA071cNjXr7o29N4dYx6hmkoig=,tag:fwOW66pem0weCTIy8FL0zA==,type:str]
type: ENC[AES256_GCM,data:QCo7eGbh,iv:m6Bx5CDZC6vuAMJr8JJLKeG+BMzLE9v9vRv4VRLaEkM=,tag:DIGtQDv/5xj9zcYrK1f4NQ==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:XkkutFjKOQ==,iv:vY6KUeQEPe/Gq6Q+JKdNnyRbCh9MFzJsV4YlLg3AwGM=,tag:7ZIfAq3BXBg6NIjwGvypFA==,type:str]
    admin-password: ENC[AES256_GCM,data:b/6+12A9r9tIZOP+tCD7ALv/,iv:flqLg6dTEfy5RZFjRZiy5XF/ep2mDthljogWDHD+m8I=,tag:EINZZHZ31U1IudDhEu2pig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1msk44qnlr795tc4m7ddw5z7sue7849nhll4wnx2qt3ruaesgye0q2rmx27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieWlFMmNOZytxZkhiSk9S
            S2Q5Y1haQVAvSXFMVHlid3BGUmdVcTlTTWtnCm1kcU8wTktFbmwwZjM5VEFIRjcw
            c1BXMFlQSWJvcWoyYUErbWFER28wWkUKLS0tIHhUR0w3azZGc01BU2FJM1FTWHFV
            RUpUYVV4R3ZVdzBVQ29sdUlsQzlzOEEKLLkokhasWSgtaCcyZcy3eeaRYwdXbPXL
            G90WPyuZ2B4K9TUS6N7mxYzW/pJrk9hvQWWFK/nhMXwCiAYFMFV5jA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T03:15:16Z"
    mac: ENC[AES256_GCM,data:pVR305+DQDiDvFSZBXAgVr/S+S0390u/y+Td6mxU8F+zprAJdNniXqJOpwxgYy+k0tvX+B8mYBD0Kko1aDQzEGIk56x1WPfG1y2pUDpR0hM3ri/gumbaRxP4JnHQClcHQlaNy3Xh0FSRb4HmPDz4/HQDOgNQHCKzW+ZD/oGqKwQ=,iv:pPZQa3/jwUnEjsJpmvicU6HDbtD89FvCcxBO+JU+fvw=,tag:y69rDzQH2fDG5qZcR7iraQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
