apiVersion: ENC[AES256_GCM,data:xwg=,iv:0Pm4fFpxY4/zYNt0Wb8TpvyEF8yA20h0BOz+KWsOs+k=,tag:YafkVFtWuaH40lOk5pVr0A==,type:str]
kind: ENC[AES256_GCM,data:WhjQb6lw,iv:WqCFtx6eMsXE/VMqcWpAoVcaULSMEFobyrDK4ruhgE8=,tag:1nbTYM37DKsEimu3KKKvpQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9ohIuERLNSqZ+v/ZJA==,iv:xewHfntiD/5tjlzRZn+ceoRA9GJHJ11w7i6YvZyni4s=,tag:hxqEUYl7jc5c5ucU9eLpLg==,type:str]
    namespace: ENC[AES256_GCM,data:USN2YL6HwzrZBg==,iv:411nUyjqzKOIo9vLMzZX4RsUFvd5vYTfl0XX3wJNU5A=,tag:OXNsnq/Drk/h8OvO4Bm/qw==,type:str]
type: ENC[AES256_GCM,data:enW/zgop,iv:mjbGqrX6kuZarA8bc0tTM0nIBTKoYn3WuYuEZH0+wDc=,tag:/HVnytuvRc7gzOA9l5UqOw==,type:str]
data:
    admin-user: ENC[AES256_GCM,data:/3tv0VBhiPmwwl50,iv:0jcgzfFF+Cd7VrbTsLpck/r33iaJVur2QnBurV6h8CM=,tag:u/XFmB2kZ9XyQUs4A+a9jQ==,type:str]
    admin-password: ENC[AES256_GCM,data:bJPZTqw54EVGo9LfUi0GWFH+Qh7/xxEBCWx1uA==,iv:kB1yAFtienUK+GI5+wD0R1S+j0CR7WSRqZzNkNfscUo=,tag:FkNWU90tuPYji22iMMkfEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1msk44qnlr795tc4m7ddw5z7sue7849nhll4wnx2qt3ruaesgye0q2rmx27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDd0M0MlFzenkvVjNhUms2
            RndreVBIUjdHUUpWYjJXMk53bi9DZjdWOVZrCnJ3R3dWU1NJYmlBd090N1NDVlN3
            OERKQzM0RWxtWWQ0QXZSNjR1ZVlTdzAKLS0tIEpqNVFzM1RYVHYvNTMyVjRqQnBP
            NEp2Sys4Y2hmVzlmdC9QSmpZcStjY1EKAEb3sI4lHN9lzJpmIPkZYOtQWSqUFEEJ
            xtP3KMwmCBdb33mFT3NZ8ZpBiQXS34vTCjlNtvd8uhMv7J7ji/sKxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T04:30:12Z"
    mac: ENC[AES256_GCM,data:Fp50uK6UBYVWHAp052HeV4jSM2BvMyOLSgPfTmKTiKEFpKuOOqcBjV1EymIuEwKo2bh/fCGZ8iEXQWhldAY0Qc0OI4C7wWi0v4n+PUnmHZeeP53b/Kh9w88LlJQzjwGtQrGQ1kldvINKKiySv63X5nrfLdrLIfRzF7XEOz4XF14=,iv:Qa/5xA4TJ1HS4Krk/L+BBa36LxkIDBdAbbg2DBne6J4=,tag:Pz88UOyQ8IaOoMIwkNnQ4g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
