apiVersion: ENC[AES256_GCM,data:XLI=,iv:umHdFONT3xNFa94XGSzrmlXJCX2D2f47yLPAajnZvr0=,tag:VO3wadph8wxCoe0MPieX9Q==,type:str]
data:
    rootUser: ENC[AES256_GCM,data:JAP67vkUMPA=,iv:Ohpui7rQxCnXKrKNqOPcwKfuaszj8VH6L9DsV8xXUKo=,tag:F3Do6nnvwzYuJXE1nWwCGQ==,type:str]
    rootPassword: ENC[AES256_GCM,data:/yBR0HLJEjKEteqHouPC2dva7pcbVuFXNOSlKg==,iv:Jk57UiYnRi2nMAvB9AZv/wzxrJcq49vZYGFSY3rki9c=,tag:+hQB1yAk8OL6zwyqvRgDkw==,type:str]
kind: ENC[AES256_GCM,data:ODE3/bpa,iv:jfblCtmjCHPo3W4VjtXDxqoIbFqhO/tL2VX6OSCDO8A=,tag:7rgjV8s9oWcqGzp0L/EkQg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eQ345iMJTjRicIkMyelE70M=,iv:ZwdZhvyWj5CBbZ9xdD0g/aXXXibNV2WsV8WD/1HJijU=,tag:wIgFTqO9jnoFpD/e1CC8xw==,type:str]
    namespace: ENC[AES256_GCM,data:sxKjZg==,iv:xCGVqzSIkIBjeRuBy+d1DeTUNaCRXFY9tO0FYhhD6QU=,tag:0++GnjznW081FuuX4PU8SQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1msk44qnlr795tc4m7ddw5z7sue7849nhll4wnx2qt3ruaesgye0q2rmx27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYllqdE03UFlTTXlQTnhh
            TlBra1FXRSsvUHdURlBDMWw5eUxvRHJQZmpRCk0yQ1JuZ3cxV0RtOEprL3ljSDYv
            WE5GaERLVW5EY1p1U0FKQ0VYUnB0ZXcKLS0tIElEd0R4UW9YVkZTM1lzOS8yb29m
            bXRJM0s1VXhqdXJqdldMUzU2RkxvZTAKZlCG1irK2Yx2JH5z2ImCnczvffYpVEwt
            87WHqmL1btE8R7DGXsdOLi5ntOmR1jhlRaSQcAZxh8qjFLS+gCAAKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T04:55:16Z"
    mac: ENC[AES256_GCM,data:CGiQVsQsCX6tvr5l1x3aiwBtw+mXkKuHz92fg4uN1wCxizyXi/eNr1y5wvLR2AIdfz7BXNl8gC7EWK10/wmLiFBuZobUaK1UC9+xpor/+4PghthCAYRNbmxVaycLLbxNnCGpK1290LTY9KFEUu/vMe5sbPjSDXfYNZKcZVC5ZRU=,iv:SRMSzfzPI0pXIx61ibcciDekjjUjf6LrTjLRxaC5TV8=,tag:DuNbfxbC2Z/cisZN1KfvDQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
