apiVersion: ENC[AES256_GCM,data:EHg=,iv:WXoNXVGaWysWq295u3NjAHOdK+tV9Gx44EvmOvME6VA=,tag:iF3P+FPRryxvE3jBRvqsNw==,type:str]
data:
    rootUser: ENC[AES256_GCM,data:XIGiXK8=,iv:2R1MF4JWSb2LZVZnOnp8UwpJrC18Jw02ds+CclKTZ3E=,tag:GgZTwd2j6qnpYmVlVzxXmA==,type:str]
    rootPassword: ENC[AES256_GCM,data:XnoaOchdmRc5Xm9rnSu3UGRBMNzwge6lf6zRjA==,iv:f9BVGMCSriDQyznEkljW3VWNqJleZacTpJKU4zYiZ0k=,tag:BU+9sMH9cGT0jKW0Yl63FA==,type:str]
kind: ENC[AES256_GCM,data:ntoBliWw,iv:Et2hZjvIm5zEHob2Q7FpnO3WIAoQrsCjepSUBJDp98I=,tag:/0dnPwdEtiDtOxZtCMatzw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:den6WONXalOvvDfPyFavu+A=,iv:x0qEqFfH7jTh1SWopzKbgqrgzAA8/wJ389zbwNRBybI=,tag:cH4tfWBGLBu9ACk0EvpqRQ==,type:str]
    namespace: ENC[AES256_GCM,data:Zqic6g==,iv:M3RWohjGHRi4ZfQ7tYnAr/YdtBcBo96eumFpeQnd87k=,tag:WrL9LKnXS7LcrVSe0wMIFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1msk44qnlr795tc4m7ddw5z7sue7849nhll4wnx2qt3ruaesgye0q2rmx27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSGdSZlQzelRnOTNyQThp
            UHVTS3hXVDBhUEdYbm03Umdtb0tWbWNFTmw4Ck95cTU0b0hVUEw0K1RSaFUyYVFi
            U2JhTVFSRGs2TEhwVzFIcGk3VS92a3MKLS0tIDdySEgva3RTZFdUcjM4S0ppaVA0
            Z3JCcDl4b21rOW5oTEFDN3kyNG44ODAKjGjbxjwUIprIPsc2ON2uuTFq0k9uHUmN
            HVrXAJXhFabnNRBjQDI2MkqfZ7hZnjw9EtM51/qse+mFinm36T4cqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T04:35:18Z"
    mac: ENC[AES256_GCM,data:tBo30SEXP/sk0jUKGaNuVKMoF7pSX2ZN26e8Gg5hLyeMR+KUdBv64hgRkjjuXQ0UPTuqRMIJRfKmOyTXtuC7P5fTAdvga14lxOWjUZxtvioj4CzPKR3Q8RzQkdld1YRPvCwpvsG5FaWf/QKs2XpZe34HA3BChZ03L4Z6CGutRpE=,iv:iRAToLleP+FR1kHZaaiu2WDmhrETtcyUvcLed5LldeA=,tag:tskpX53+1t+lmUQnNMnMfg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
